### ISSUE TITLE
some page urls have encoded characters

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cy-search#5]
For example, when searching for "network" see the bottom URL "what you will learn"

<img width="1408" alt="Screen Shot 2020-10-27 at 8 12 19 AM" src="https://user-images.githubusercontent.com/2212006/97300014-3adb2480-182c-11eb-8572-759a23a32093.png">

<img width="595" alt="Screen Shot 2020-10-27 at 8 13 50 AM" src="https://user-images.githubusercontent.com/2212006/97300096-59d9b680-182c-11eb-95ca-1abd013e9ada.png">

**Comment by filiphric** [comment]
I noticed this too, but on the link. I’m not redirected properly to [Who’s behind Cypress?](https://docs.cypress.io/faq/questions/company-faq.html#Who%E2%80%99s-behind-Cypress) page
